### ISSUE TITLE
intellij idea 2018 support

### ISSUE THREAD

**Issue by cocodrino** [intellij-crystal/intellij-crystal#6]
Hi @faustinoaq it's not clear for me what project and plugin must I install on intellij idea because seems there're many forks

first I install this on idea, but it's just syntax highlight

then I builded this [repo](https://github.com/crystal-lang-tools/intellij-crystal-lang) but seems that it's not compatible with intellij idea 2018...I'd like to use scry and reading the comments seems that you achieve this using intellij lsp...basically I'd like some kind of autocompletion (I don't care if it's really basic) and debug on fly (show errors in my code after save without compile)...is it supported???

espero me puedas ayudar
gracias!!!...

**Comment by faustinoaq** [comment]
@cocodrino I have this issue too. I had done some work with this plugin and Scry. Thanks to @kingsleyh , although currently I don't have enough time due to college. I have too much things to do :sweat_smile: I hope to get some free time after finish my work at college.

Also feel free to collaborate with new PRs, any contribution is welcome :+1: 

BTW, looks like community is working on Scry 0.25.X compatibility again. Thanks to @bmulvihill :tada: https://github.com/crystal-lang-tools/scry/pull/131

**Comment by vlad-ro** [comment]
For IDEA 2018.2 an onwards compatibility feel free to use this PR:
https://github.com/crystal-lang-tools/intellij-crystal-lang/pull/5

**Comment by vlad-ro** [comment]
A new version of the plugin with support for 2018.2 onwards has been published: https://plugins.jetbrains.com/plugin/11232-crystal-language-support-updated-for-v2018-2-onwards
It is a fork as the original plugin got dormant.
